name: Java CI with JUnit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Install JUnit + Mockito
      run: |
        mkdir -p lib
        wget -O lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar
        wget -O lib/mockito-core.jar https://repo1.maven.org/maven2/org/mockito/mockito-core/5.5.0/mockito-core-5.5.0.jar
    - name: Compile
      run: javac -cp "lib/*:." *.java test/java/*.java
    - name: Run Tests
      run: java -jar lib/junit-platform-console-standalone.jar --class-path . --scan-class-path
